import Head from 'next/head';
// import { Inter } from 'next/font/google';
import type { FC } from 'react';
import Home from './home';

// const inter = Inter({ subsets: ['latin'] });

const HomeRoot: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name={'description'} content={'Generated by create next app'} />
        <meta
          name={'viewport'}
          content={'width=device-width, initial-scale=1'}
        />
        <link rel={'icon'} href={'/favicon.ico'} />
      </Head>
      <main>
        <Home />
      </main>
    </>
  );
};

export default HomeRoot;
